config/routes.rb
Epr::Application.routes.draw do
  resources :reviews 


  resources :reports


  resources :proposals do
    get "index"

    get "assign"

    get "review"

    get "show"
  end

  resources :projects do
    get "add_partner" => "projects#get_add_partner"

    put "add_partner" => "projects#post_add_partner"

    get "submit_proposal" => "projects#get_submit_proposal"

    put "submit_proposal" => "projects#post_submit_proposal"

    get "review" => "projects#review"
    get "report" => "projects#report"
    put "report" => "projects#put_report"
  end



  devise_for :users
  scope "/admin" do
    resources :users
  end

  get "home/index"

  root :to => "home#index"

end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  attr_accessible :abstract, :project_id, :title, :user_id, :document, :document_cache,:reviewed ,:assigned
  validates :title, :presence => true
  validates :abstract, :presence => true
  validates :document, :presence => true
  validates :user , :presence => true
  belongs_to :user
  belongs_to :project
  mount_uploader :document, ProposalUploader
  scope :un_assigned , where(:assigned => nil)
end

app/controllers/proposals_controller.rb
class ProposalsController < ApplicationController
  # GET /proposals
  # GET /proposals.json
  def index
    @proposals = Proposal.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @proposals }
    end
  end

  # GET /proposals/1
  # GET /proposals/1.json
  def show
    @proposal = Proposal.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @proposal }
    end
  end

  # GET /proposals/new
  # GET /proposals/new.json
  def new
    @proposal = Proposal.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @proposal }
    end
  end

  # GET /proposals/1/edit
  def edit
    @proposal = Proposal.find(params[:id])
  end

  # POST /proposals
  # POST /proposals.json
  def create
    @proposal = Proposal.new(params[:proposal])

    respond_to do |format|
      if @proposal.save
        format.html { redirect_to @proposal, notice: 'Proposal was successfully created.' }
        format.json { render json: @proposal, status: :created, location: @proposal }
      else
        format.html { render action: "new" }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /proposals/1
  # PUT /proposals/1.json
  def update
    @proposal = Proposal.find(params[:id])

    respond_to do |format|
      if @proposal.update_attributes(params[:proposal])
        format.html { redirect_to @proposal, notice: 'Proposal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @proposal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /proposals/1
  # DELETE /proposals/1.json
  def destroy
    @proposal = Proposal.find(params[:id])
    @proposal.destroy

    respond_to do |format|
      format.html { redirect_to proposals_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/proposal_helper.rb
module ProposalHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/views/proposals/_form.html.erb
<%= simple_form_for(@proposal) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
	  <%= f.input :user_id, :as => :hidden, :input_html => {:value => current_user.id} %>
	    <%= f.input :title, :required => true %>
	    <%= f.input :abstract, :required => true %>
	    <% if f.object.document? %>
	        <%= link_to f.object.document.url, :class => "button small" do %>
	            <%= f.object.document.file.filename %>
	            <i class="icon-download-alt"></i>
	        <% end %>
	    <% end %>
	    <%= f.input :document, :as => :file, :required => true %>
	    <%= f.hidden_field :document_cache %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/proposals/edit.html.erb
<h1>Editing proposal</h1>

<%= render 'form' %>

<%= link_to 'Show', @proposal %> |
<%= link_to 'Back', proposals_path %>

app/views/proposals/index.html.erb
<h1>Listing proposals</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Project</th>
    <th>Reviewed</th>
    <th>Assigned</th>
    <th>Submitted By</th>
  </tr>

<% @proposals.each do |proposal| %>
  <tr>
	  <td><%= proposal.title %></td>
	  <td><%= proposal.project.title %></td>
	  <td>
	  <%= check_box_tag 'proposal', 'reviewed', proposal.reviewed, :disabled => true %>
	  </td>
	  <td><%= check_box_tag 'proposal', 'assigned', proposal.assigned, :disabled => true %></td>
	  <td>
		  <% if proposal.user %>
		  <%= proposal.user.full_name %>
		  <%end%>
	  </td>
    <td>
	  <% if not proposal.assigned %>
	  	<%= link_to 'Review', new_review_path %>
	  <%end%>
	</td>
    
    <td><%= link_to 'View', proposal %></td>
   <td><%= link_to 'Edit', edit_proposal_path(proposal) %></td>
  </tr>
<% end %>
</table>

<br />

 

app/views/proposals/new.html.erb
<h1>New proposal</h1>

<%= render 'form' %>

<%= link_to 'Back', proposals_path %>

app/views/proposals/show.html.erb
<p id="notice"><%= notice %></p>

<table border="0" cellspacing="5" cellpadding="5">
	<tr><th><%=@proposal.title %></th></tr>
	<tr><td>
		Id
	</td>
	<td>
		<%=@proposal.id %>
	</td>
</tr>
	<tr><td>
		Title
	</td>
	<td>
		<%=@proposal.title %>
	</td>
</tr><tr><td>
		Abstract
	</td>
	<td>
		<%=@proposal.abstract %>
	</td>
</tr>
	<tr><td>
		File
	</td>
	<td>
	    <% if @proposal.document? %>
	        <%= link_to @proposal.document.url, :class => "button small" do %>
	            <%= @proposal.document.file.filename %>
	            <i class="icon-download-alt"></i>
	        <% end %>
	    <% end %>
		
	</td>
</tr>
</table>

<%= link_to 'Back', proposals_path %>