config/routes.rb
Epr::Application.routes.draw do
  resources :reviews 


  resources :reports


  resources :proposals do
    get "index"

    get "assign"

    get "review"

    get "show"
  end

  resources :projects do
    get "add_partner" => "projects#get_add_partner"

    put "add_partner" => "projects#post_add_partner"

    get "submit_proposal" => "projects#get_submit_proposal"

    put "submit_proposal" => "projects#post_submit_proposal"

    get "review" => "projects#review"
    get "report" => "projects#report"
    put "report" => "projects#put_report"
  end



  devise_for :users
  scope "/admin" do
    resources :users
  end

  get "home/index"

  root :to => "home#index"

end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  # GET /reviews
  # GET /reviews.json
  def index
    @reviews = Review.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reviews }
    end
  end

  # GET /reviews/1
  # GET /reviews/1.json
  def show
    @review = Review.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/new
  # GET /reviews/new.json
  def new
    @review = Review.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @review }
    end
  end

  # GET /reviews/1/edit
  def edit
    @review = Review.find(params[:id])
  end

  # POST /reviews
  # POST /reviews.json
  def create
    @review = Review.new(params[:review])

    respond_to do |format|
      if @review.save
        if @review.status == "Approved"
          @review.proposal.project.status ="approved"
          @review.proposal.project.save()
        else
          @review.proposal.project.status ="rejected"
          @review.proposal.project.save()
        end
        format.html { redirect_to @review, notice: 'Review was successfully created.' }
        format.json { render json: @review, status: :created, location: @review }
      else
        format.html { render action: "new" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reviews/1
  # PUT /reviews/1.json
  def update
    @review = Review.find(params[:id])

    respond_to do |format|
      if @review.update_attributes(params[:review])
        format.html { redirect_to @review, notice: 'Review was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @review.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reviews/1
  # DELETE /reviews/1.json
  def destroy
    @review = Review.find(params[:id])
    @review.destroy

    respond_to do |format|
      format.html { redirect_to reviews_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/reviews/_form.html.erb
<%= simple_form_for(@review) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    
    <%= f.collection_select(:proposal_id, Proposal.un_assigned, :id, :title, prompt: "Select a proposal")%>
	<%= f.collection_select(:user_id, User.supervisors, :id, :email, prompt: "Select a Supervisor")%>
    <%= f.input :comment %>
	 <%= f.input :status, collection: ["Approved","Rejected"], :required => true,prompt: "Select status" %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/reviews/edit.html.erb
<h1>Editing review</h1>

<%= render 'form' %>

<%= link_to 'Show', @review %> |
<%= link_to 'Back', reviews_path %>

app/views/reviews/index.html.erb
<h1>Listing reviews</h1>

<table>
  <tr>
    <th>Proposal</th>
    <th>User</th>
    <th>Comment</th>
    <th>Status</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @reviews.each do |review| %>
  <tr>
    <td><%= review.proposal_id %></td>
    <td><%= review.user_id %></td>
    <td><%= review.comment %></td>
    <td><%= review.status %></td>
    <td><%= link_to 'Show', review %></td>
    <td><%= link_to 'Edit', edit_review_path(review) %></td>
    <td><%= link_to 'Destroy', review, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to "New Review" , new_review_path %>
 

app/views/reviews/new.html.erb
<h1>New review</h1>

<%= render 'form' %>

<%= link_to 'Back', reviews_path %>

app/views/reviews/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Proposal:</b>
  <%= @review.proposal_id %>
</p>

<p>
  <b>User:</b>
  <%= @review.user_id %>
</p>

<p>
  <b>Comment:</b>
  <%= @review.comment %>
</p>

<p>
  <b>Status:</b>
  <%= @review.status %>
</p>


<%= link_to 'Edit', edit_review_path(@review) %> |
<%= link_to 'Back', reviews_path %>