config/routes.rb
Epr::Application.routes.draw do
  resources :reviews 


  resources :reports


  resources :proposals do
    get "index"

    get "assign"

    get "review"

    get "show"
  end

  resources :projects do
    get "add_partner" => "projects#get_add_partner"

    put "add_partner" => "projects#post_add_partner"

    get "submit_proposal" => "projects#get_submit_proposal"

    put "submit_proposal" => "projects#post_submit_proposal"

    get "review" => "projects#review"
    get "report" => "projects#report"
    put "report" => "projects#put_report"
  end



  devise_for :users
  scope "/admin" do
    resources :users
  end

  get "home/index"

  root :to => "home#index"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user
      if user.is_student?
        can :create, Project
      elsif user.is_projects_coordinator?
        can :manage, Project
        can :manage, User
        can :manage, Proposal
        can :manage, Report
        can :manage, Review
      elsif user.is_supervisor?
        can :manage, Report, :supervisor_id => user.id
        can :manage, Report, :co_supervisor_id => user.id
        can :manage, Review , :user_id => user.id
      end
      can :manage, Project, :user_id => user.id
    end

  end
end

app/models/project.rb
class Project < ActiveRecord::Base
  attr_accessible :number_of_participants, :status, :title, :project_members_attributes,:proposals_attributes, :reports_attributes
  validates :title, :presence => true
  validates :number_of_participants, :presence => true
  validates :status, :presence => true
  validates :status, :inclusion => {:in => %w(new participants concept approved rejected cleared complete)}
  validates_uniqueness_of :title
  belongs_to :user
  has_many :project_members
  has_many :proposals
  has_many :reports
  accepts_nested_attributes_for :project_members, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :proposals, :reject_if => :all_blank, :allow_destroy => true
  accepts_nested_attributes_for :reports, :reject_if => :all_blank, :allow_destroy => true

end

app/models/project_member.rb
class ProjectMember < ActiveRecord::Base
  attr_accessible :email, :name
  validates :email, :presence => true
  validates :name, :presence => true
  belongs_to :project
end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  attr_accessible :abstract, :project_id, :title, :user_id, :document, :document_cache,:reviewed ,:assigned
  validates :title, :presence => true
  validates :abstract, :presence => true
  validates :document, :presence => true
  validates :user , :presence => true
  belongs_to :user
  belongs_to :project
  mount_uploader :document, ProposalUploader
  scope :un_assigned , where(:assigned => nil)
end

app/models/report.rb
class Report < ActiveRecord::Base
  attr_accessible :abstract, :document, :project_id, :status, :title, :user_id
  belongs_to :user
  belongs_to :project
  validates :title , :presence => true
  validates :abstract , :presence => true
  validates :document , :presence => true
  mount_uploader :document, ProposalUploader
end

app/models/review.rb
class Review < ActiveRecord::Base
  attr_accessible :comment, :proposal_id, :status, :user_id
  belongs_to :user
  belongs_to :proposal
  validates :status , :presence => true
end

app/models/role.rb
class Role < ActiveRecord::Base
  has_and_belongs_to_many :users, :join_table => :users_roles
  belongs_to :resource, :polymorphic => true
  
  scopify
end

app/models/user.rb
class User < ActiveRecord::Base
  rolify
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :user_type, :registration_number, :academic_programme, :full_name
  # attr_accessible :title, :body
  validates :user_type, :presence => true
  validates :full_name, :presence => true
  validates :registration_number, :presence => true, :if => :is_student?
  validates_uniqueness_of :registration_number, :if => :is_student?
  validates :academic_programme, :presence => true, :if => :is_student?
  has_many :projects
  scope :supervisors , where(:user_type => "Super")
  def is_student?
    user_type == "Student"
  end

  def is_public?
    user_type == "Public"
  end

  def is_projects_coordinator?
    user_type == "PC"
  end
  def is_supervisor?
    user_type == "Super"
  end

  def password_required?
    (!password.blank? && !password_confirmation.blank?) || new_record?
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @reports }
    end
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
    @report = Report.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/new
  # GET /reports/new.json
  def new
    @report = Report.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @report }
    end
  end

  # GET /reports/1/edit
  def edit
    @report = Report.find(params[:id])
  end

  # POST /reports
  # POST /reports.json
  def create
    @report = Report.new(params[:report])

    respond_to do |format|
      if @report.save
        format.html { redirect_to @report, notice: 'Report was successfully created.' }
        format.json { render json: @report, status: :created, location: @report }
      else
        format.html { render action: "new" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /reports/1
  # PUT /reports/1.json
  def update
    @report = Report.find(params[:id])

    respond_to do |format|
      if @report.update_attributes(params[:report])
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report = Report.find(params[:id])
    @report.destroy

    respond_to do |format|
      format.html { redirect_to reports_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :authenticate_user!
  load_and_authorize_resource

  def index
  end


  def show
  end


  def new
    @user = User.new
  end


  def edit
  end


  def create
    @user = User.new(params[:user])

    if @user.save
      redirect_to @user, notice: 'User was successfully created.'
    else
      render action: "new"
    end
  end


  def update

    if @user.update_attributes(params[:user])
      redirect_to @user, notice: 'User was successfully updated.'
    else
      render action: "edit"
    end
  end


  def destroy
    @user.destroy
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/project_steps_helper.rb
module ProjectStepsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/proposal_helper.rb
module ProposalHelper
end

app/helpers/proposals_helper.rb
module ProposalsHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_header.html.erb
<header class="white band padded">
  <div class="container pad-top">
    <div class="row">
      <div class="one third padded">

        <h1 class="responsive">
          <a href="/">
            ECE Projects Repository
          </a>
        </h1>

      </div>
      <div class="two thirds padded">
        <nav class="inline pull-right">
          <ul>
            <%= render :partial => 'login_items' %>


          </ul>
        </nav>
      </div>
    </div>
  </div>
</header>

app/views/layouts/_sidebar.html.erb
<aside class="one fifth padded border-right">
  <h3>
    <i class="icon-reorder"></i>
    Navigation
  </h3>
  <nav class="nav">
    <ul>
      <li>
        <%= link_to "Home", root_path %>
      </li>
      <li>
        <% if can? :create, Project %>
            <%= link_to "New Project", new_project_path %>
        <% end %>
      </li>
      <li>
        <% if can? :manage, Project %>
            <%= link_to "Projects", projects_path %>
        <% end %>
      </li>
      <li>
        <% if can? :manage, User %>
            <%= link_to "Users", users_path %>
        <% end %>
      </li>

      <li>
        <% if can? :manage, Proposal %>
            <%= link_to "Proposals", proposals_path %>
        <% end %>
      </li>
      <li>
        <% if can? :manage, Report %>
            <%= link_to "Reports", reports_path %>
        <% end %>
      </li>
      <li>
        <% if can? :manage, Review %>
            <%= link_to "Reviews", reviews_path %>
        <% end %>
      </li>

    </ul>
  </nav>


</aside>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1, maximum-scale=1">
    <title><%= content_for?(:title) ? yield(:title) : "ECE Projects Repository" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->    
    <%= stylesheet_link_tag "application", :media => "all" %>
  </head>
	<body>
		
		<%= render :partial => "layouts/header"%>
		
		<div class="container gap-top">		
			<div class="row">
				<%= render :partial => "layouts/sidebar"%>
	
				<section class="four fifths
					padded">
						
					<%= groundwork_flash %>
				
					<%= yield %>
					
				</section>
			</div>
	
			<footer class="footer align-center">
				<p>&copy; EPR 2013</p>
			</footer>
	
		</div> <!-- /container -->
		<%= javascript_include_tag "application" %>
  </body>
</html>